
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 19 2026 14:00:48 IST (May 19 2026 08:30:48 UTC)

// Verification Directory fv/hamming_main 

module hamming_main(mess, out);
  input [7:0] mess;
  output [11:0] out;
  wire [7:0] mess;
  wire [11:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_9;
  wire n_10, n_11;
  assign out[2] = mess[0];
  assign out[4] = mess[1];
  assign out[5] = mess[2];
  assign out[6] = mess[3];
  assign out[8] = mess[4];
  assign out[9] = mess[5];
  assign out[10] = mess[6];
  assign out[11] = mess[7];
  CLKXOR2X2 g179__2398(.A (n_6), .B (n_10), .Y (out[1]));
  CLKXOR2X2 g180__5107(.A (n_1), .B (n_11), .Y (out[0]));
  OAI21XL g182__6260(.A0 (n_9), .A1 (mess[1]), .B0 (n_4), .Y (n_11));
  AOI21XL g184__4319(.A0 (mess[2]), .A1 (n_9), .B0 (n_5), .Y (n_10));
  CLKXOR2X2 g181__8428(.A (n_0), .B (n_3), .Y (out[3]));
  CLKXOR2X2 g183__5526(.A (n_6), .B (n_2), .Y (out[7]));
  NOR2XL g186__6783(.A (mess[2]), .B (n_9), .Y (n_5));
  NAND2XL g185__3680(.A (mess[1]), .B (n_9), .Y (n_4));
  CLKXOR2X1 g187__1617(.A (mess[1]), .B (mess[7]), .Y (n_3));
  XNOR2X1 g190__2802(.A (mess[4]), .B (mess[7]), .Y (n_2));
  CLKXOR2X1 g191__1705(.A (mess[4]), .B (mess[6]), .Y (n_1));
  CLKXOR2X1 g188__5122(.A (mess[2]), .B (mess[3]), .Y (n_0));
  XNOR2X1 g189__8246(.A (mess[5]), .B (mess[6]), .Y (n_6));
  XNOR2X1 g192__7098(.A (mess[0]), .B (mess[3]), .Y (n_9));
endmodule

